### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/dam-app#1]

**Comment by NguyenTrang091296** [comment]
Design ![image](https://user-images.githubusercontent.com/39818849/193005375-f5e0072c-d9cd-49cd-aeae-c3657c1195c5.png)
Actual result:
Missing welcome text
Missing function remember me
missing function forgot password
Link to dma page -> right link to dam
![image](https://user-images.githubusercontent.com/39818849/193005463-0c9e34aa-6bac-42be-88ba-a6f07f5c80be.png)
