### ISSUE TITLE
Delete folder / file

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/dam-app#10]
https://www.figma.com/proto/OAcpwQSGND0t6Dswi3ZTKP/AESIR_DAM?page-id=0%3A1&node-id=169%3A3374&viewport=409%2C-3189%2C0.5&scaling=min-zoom

**Comment by NguyenTrang091296** [comment]
I checked and I see it is working incorrect
https://youtu.be/r3lxcUP8jcA
