### ISSUE TITLE
Login app - Change the basic style 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#101]
Login app on the dev site
Compare with design DAM to clone about the style 
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=5290%3A29850&t=jdUBSTjC1zu0f0ws-0
Remember change text for each project

**Comment by NguyenTrang091296** [comment]
Width input and button : 480px
Change welcome text, text color: #0A083B change font-weight: 600
![image](https://user-images.githubusercontent.com/39818849/212013296-603ca584-b3d0-4c9d-a446-dcf79035c0ac.png)
Change text "Sign In with SSO" to "Sign in with SSO" font-size:18px and font-weight:700
Label text color:#000000, font-weight:600
asterisk color: C60202
"or" color : #8E8E8E
input border have color #D5D5D5
Lost "Remeber me" and  "Forgot password?"
"Sign in" Button : Uppercase text
Add padding between label text and input
Please help me fix cc @kakahuy113

**Comment by NguyenTrang091296** [comment]
Please help me fix padding between label and input

![Image](https://user-images.githubusercontent.com/39818849/212806719-f29611a5-1089-4ca4-8ae6-2d4f9c76cb56.png)
Please set width for input and button: 480
Check active input
Actual result:
![Image](https://user-images.githubusercontent.com/39818849/212808371-70fe4901-6344-4047-b87c-da60449fdfde.png)

Expected output:
![Image](https://user-images.githubusercontent.com/39818849/212808431-f0ee5fdf-06fc-4df5-a828-da778fe342b1.png)

**Comment by huynhngocgiau** [comment]
Please check design again : https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=5290%3A29850&t=UDg4UTsiLM616nmg-0

Change welcome text, text color: #0A083B
Change text "Sign In with SSO" to "Sign in with SSO" font-size:18px and font-weight:700
Label text color:#000000, font-weight:600
asterisk color: C60202
"OR" color : #8E8E8E
input border have color #D5D5D5
Check active input

**Comment by VanTrieuThanh** [comment]
- Change the Sign In with SSO to Sign in with SSO
- Make the spacing between OR and the line 
![image](https://user-images.githubusercontent.com/44457418/216554561-7be84491-1ccf-4ebe-88c4-380dec7ca441.png)
- The background color not change when user click on first time 
![image](https://user-images.githubusercontent.com/44457418/216555195-88c4de0a-809c-444c-a416-276394c2c274.png)
- Click on the other place it has show the background color 
![image](https://user-images.githubusercontent.com/44457418/216555464-3852be2a-0981-45b0-8efd-e29770a82173.png)

**Comment by huynhngocgiau** [comment]
Text color: Welcome to aesirx DAM Sign In to getting started.
![image](https://user-images.githubusercontent.com/79819354/219349704-aea3f912-1abb-4bec-bafe-fc695cb93631.png)

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/219541702-c14a6a24-11eb-44a9-82a5-82db42de0f12.png)
