### ISSUE TITLE
DAM - List - Missing info last modified for Folders

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/dam-app#116]
![image](https://user-images.githubusercontent.com/39818849/210918966-6f988d90-f9a2-4db6-9196-4b96d0961a9d.png)

**Comment by huynhngocgiau** [comment]
has updated
![time](https://user-images.githubusercontent.com/79819354/215016276-b5c0960e-7448-463c-a869-e6e674190bd6.png)
