### ISSUE TITLE
DAM - Left menu - Menu item when active have font-weight 600

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/dam-app#117]
Actual result: Menu item  when active have font-weight 400
![image](https://user-images.githubusercontent.com/39818849/210919973-3a7c9862-09fd-409a-b3cb-3bf2310c9cb2.png)

Expected result:Menu item when active have font-weight 600
![image](https://user-images.githubusercontent.com/39818849/210919828-6b134e4d-c7b2-4fb2-b0e9-7b70fa497ab5.png)

**Comment by VanTrieuThanh** [comment]
missing the bold in the item active ![image](https://user-images.githubusercontent.com/44457418/216537932-d2c322ec-79e3-4629-80a7-85106cb61929.png)
