### ISSUE TITLE
Language - Not Sync 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#119]
![image](https://user-images.githubusercontent.com/44457418/210927861-d1ded2c2-9d44-4a3e-9a6c-cd0ba8d5f6e0.png)

**Comment by kakahuy113** [comment]
we just do for eng and vi another translation please give me a file or some one in community can help about it open for PR

**Comment by huynhngocgiau** [comment]
![image](https://user-images.githubusercontent.com/79819354/212034042-4dc92ae1-e5b1-4f13-8089-f2b6a2b3997d.png)
![image](https://user-images.githubusercontent.com/79819354/212033444-b01078ec-a579-4eac-be44-f6b384ab7280.png)
![image](https://user-images.githubusercontent.com/79819354/212034445-adbe7470-78be-431b-adf9-055eaf406aa1.png)

**Comment by kakahuy113** [comment]
duplicate #141 please help me close it if see any ping me

**Comment by huynhngocgiau** [comment]
There is a problem that when switching to another language, there is a place where the update can't be immediately f5 or choose another item
![transDansk](https://user-images.githubusercontent.com/79819354/212591040-354c8ca5-00cc-4d68-84e7-0546361194ac.png)

**Comment by kakahuy113** [comment]
duplicate #141

**Comment by thaoredweb** [comment]
Let double check this issue when 119 is done @huynhngocgiau @VanTrieuThanh 
https://github.com/aesirxio/dam-app/issues/141

**Comment by VanTrieuThanh** [comment]
2 task not duplicate chị @thaoredweb: 119 for Sync Translate App, 141 for Integration App (PIM)

**Comment by kakahuy113** [comment]
it the same c @VanTrieuThanh it work the same so if you check #119 good please help me close for #141  too

**Comment by huynhngocgiau** [comment]
All language
![image](https://user-images.githubusercontent.com/79819354/216288562-4a3bde6e-6719-4212-89ce-4cea9f070b9c.png)

**Comment by VanTrieuThanh** [comment]
VN not translate My asset, Your Digital Assets to Asset của tôi,  Digital Assets của tôi
![image](https://user-images.githubusercontent.com/44457418/216536171-694f5b2d-1239-4f43-a344-1574230cb347.png)

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/216553625-486b0967-e9e7-4938-acdd-4600e3c83762.png)
![image](https://user-images.githubusercontent.com/79819354/216553724-664ac824-584b-44a9-88d4-b88c26f382da.png)
