### ISSUE TITLE
Sort not working 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#120]
![image](https://user-images.githubusercontent.com/44457418/210928686-c69de642-cf89-45a1-8953-30b38194fe0e.png)

**Comment by NguyenTrang091296** [comment]
Hi @kakahuy113 I checked but i see it is working incorrect
![image](https://user-images.githubusercontent.com/39818849/211976217-cb9522ad-1377-4717-a685-f6000a92581c.png)

**Comment by kakahuy113** [comment]
a @NguyenBao10 please help me with this i had create task for BE

**Comment by huynhngocgiau** [comment]
It is working incorrect
![sort](https://user-images.githubusercontent.com/79819354/215018130-c3342c6f-5aec-4514-b860-f964091b5e7a.png)

**Comment by kakahuy113** [comment]
Did it order again or it the same from begin @huynhngocgiau  ? if it  arrange but not true BE need to look e

**Comment by thaoredweb** [comment]
@NguyenBao10 Can you take a look at this issue?

**Comment by thaoredweb** [comment]
please check for special cases: capital letter, number, space, lower-case letters

**Comment by VanTrieuThanh** [comment]
Not working on the dev site 
![image](https://user-images.githubusercontent.com/44457418/216546881-24e1ea1a-8087-474b-8883-cdcfed28e20e.png)

**Comment by CongThuong** [comment]
MR is merged on dev-site, please take a look again chi @VanTrieuThanh E @kakahuy113

**Comment by thaoredweb** [comment]
@kakahuy113 can you check the issue. It worked at backend BUT FE still not config e

**Comment by thaoredweb** [comment]
It worked okie on dev site. please merge to live a @lunguyenhat

**Comment by CongThuong** [comment]
It's on master, please take a look chi @thaoredweb
