### ISSUE TITLE
Rename folder - Change the "Create" to "Save" button

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#121]
![image](https://user-images.githubusercontent.com/44457418/210940816-30138651-3172-4dc3-88aa-56227e2c6a62.png)

**Comment by kakahuy113** [comment]
duplicate #109

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/212620413-b8677e11-60f8-4ec0-99b6-f4fccdb1fbe7.png)
still not update when user click on Rename on the demo site
