### ISSUE TITLE
Error when user click on "Download Folder"

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#122]
![image](https://user-images.githubusercontent.com/44457418/210941564-877cbd23-b1a4-422c-81e4-5a61df91f133.png)

**Comment by kakahuy113** [comment]
folder can not download so i will hide download item when right click folder @NguyenTrang091296

**Comment by NguyenTrang091296** [comment]
No it need work with folder only hide preview folder

**Comment by kakahuy113** [comment]
so we don't need review for Folders @NguyenTrang091296 ? i remember we need to see size of the folders

**Comment by CongThuong** [comment]
I've changed the API to downloadFiles.
So you can pass collectionIds[] and assetIds[] in Body to download

{{domain}}/index.php?webserviceClient=site&webserviceVersion=1.0.0&option=dam_collection&task=downloadFiles&api=hal

![image](https://user-images.githubusercontent.com/94885770/216526396-181df9b8-5d35-4adb-8bd8-0d7343a160a0.png)

**Comment by kakahuy113** [comment]
wrong image @CongThuong

**Comment by CongThuong** [comment]
> wrong image @CongThuong

Thanks Em, edited

**Comment by VanTrieuThanh** [comment]
Waiting the task on the gitlab https://gitlab.redweb.dk/aesirx/aesir-webservice/-/issues/254 it still complete
