### ISSUE TITLE
Create folder - Show popup create folder the second time when user click on the Enter in keyboard 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#124]
http://recordit.co/ssJ3rc2xpr

**Comment by NguyenTrang091296** [comment]
I checked and I see it still error
[screen-capture (9).webm](https://user-images.githubusercontent.com/39818849/211496352-39fc7261-089c-4e32-ad11-93a8ccb15541.webm)

**Comment by VanTrieuThanh** [comment]
demo site still showing on 
![image](https://user-images.githubusercontent.com/44457418/212619510-76b07d2b-0113-48d5-a4a0-46542c10736d.png)
