### ISSUE TITLE
Sidebar - 'Active' menu

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#130]
- No border radius when active menu
- Wrong arrow icon and color
![Image](https://user-images.githubusercontent.com/118497336/211448697-d882f297-ff7d-4951-bc24-4ad3ec764f43.png)

**Comment by VanTrieuThanh** [comment]
Still border radius and wrong arrow icon and color ![image](https://user-images.githubusercontent.com/44457418/216537653-c1cb744f-ce33-4aa6-816c-76d8989ecf2f.png)
