### ISSUE TITLE
Improve Darkmode - UI

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#131]
Check and improve darkmode

![Image](https://user-images.githubusercontent.com/118497336/211449220-68cf0807-5856-49e8-87b8-ce13def6fa52.png)

Design:
https://www.figma.com/proto/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?page-id=552%3A1816&node-id=6320%3A33452&viewport=208%2C731%2C0.06&scaling=min-zoom

**Comment by huynhngocgiau** [comment]
Please check again a @kakahuy113 
![Screenshot from 2023-02-24 08-49-10](https://user-images.githubusercontent.com/79819354/221072220-41874006-2bee-4352-8f4d-33e8945981a5.png)

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/221108708-54cdce53-88cb-464d-b6fa-21e4c4fb756c.png)
