### ISSUE TITLE
Create folder / Upload file - Text on button has been line drop when title folder too big

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/dam-app#134]
Actual result: Text on button has been line drop when title folder too big

![Image](https://user-images.githubusercontent.com/39818849/211499273-722c77ff-2b41-4376-b7e7-f15173935556.png)

**Comment by huynhngocgiau** [comment]
has updated
![folder](https://user-images.githubusercontent.com/79819354/215015851-19a54a8c-51bb-4b1f-8461-765a5f6a30fa.png)
