### ISSUE TITLE
[Avatar] show letter avatar when there is no image

### ISSUE THREAD

**Issue by hongdtb41** [aesirxio/dam-app#139]
On each demo sites ,  when the user is logged in, his letters avatar will display.

**Comment by kakahuy113** [comment]
duplicate #140

**Comment by kakahuy113** [comment]
close this task if you see dulicate

**Comment by huynhngocgiau** [comment]
> close this task if you see dulicate

It's another issue a @kakahuy113 
His letters avatar will display when the user hasn't updated his profile picture

**Comment by huynhngocgiau** [comment]
worked
![image](https://user-images.githubusercontent.com/79819354/220560634-43464791-94f3-4ffa-a1b0-6e88d09ba9e7.png)
