### ISSUE TITLE
[Avatar] could change profile picture

### ISSUE THREAD

**Issue by hongdtb41** [aesirxio/dam-app#140]

**Comment by huynhngocgiau** [comment]
Avatar has not been updated yet
![Screenshot from 2023-02-17 10-30-49](https://user-images.githubusercontent.com/79819354/219542746-f766526d-4152-4c23-af03-463c9c6d88e2.png)

**Comment by kakahuy113** [comment]
i test and see it updated?

**Comment by huynhngocgiau** [comment]
worked 
![image](https://user-images.githubusercontent.com/79819354/219870850-c836cd9c-6b4e-4f46-949e-fd96ba3c25d2.png)
