### ISSUE TITLE
Intergration DAM translate 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#141]

**Comment by huynhngocgiau** [comment]
has update

**Comment by huynhngocgiau** [comment]
But there is a problem that when switching to another language, some places don't update immediately, you have to f5 or choose another item


![Image](https://user-images.githubusercontent.com/79819354/212587306-070598ec-f58d-43e2-9016-3c37dbbc1193.png)

**Comment by VanTrieuThanh** [comment]
create the folder 
<img width="1420" alt="Screen Shot 2023-01-18 at 13 54 35" src="https://user-images.githubusercontent.com/44457418/213104511-202e9d56-3041-4f3e-b4c3-3aadf179c99a.png">
<img width="1420" alt="Screen Shot 2023-01-18 at 13 58 02" src="https://user-images.githubusercontent.com/44457418/213104978-570a63e1-e45a-4151-b0ed-fc495de102b9.png">

**Comment by kakahuy113** [comment]
duplicate #43

**Comment by huynhngocgiau** [comment]
Need doc/set up docker to check task

**Comment by kakahuy113** [comment]
@toanredweb @PhuLy88 a @vietredweb a @lklong709

**Comment by kakahuy113** [comment]
@toanredweb you need to pass lang and theme attributes look at this example https://github.com/aesirxio/mcms-app/blob/develop/src/containers/DamPage/index.jsx

**Comment by huynhngocgiau** [comment]
@toanredweb 
![image](https://user-images.githubusercontent.com/79819354/220074058-ff77000d-9a77-418f-b907-2dc37c550712.png)
