### ISSUE TITLE
Left Menu doesn't show new folder

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/dam-app#142]
Left menu doesn't show new folder, need to refresh page to show
![showFolder](https://user-images.githubusercontent.com/79819354/212041166-02f8160a-7587-4291-bc8a-5da6fe061ef8.png)

**Comment by OscarIboy** [comment]
It looks fine now.
![Captura de pantalla -2023-06-01 12-27-43](https://github.com/aesirxio/dam-app/assets/8058963/19e13299-a3f7-4aec-ad0d-d13b732ff826)
![Captura de pantalla -2023-06-01 12-27-48](https://github.com/aesirxio/dam-app/assets/8058963/cc1fff7d-e419-4609-8c53-4ef3566e7e27)
