### ISSUE TITLE
Wrong message when upload duplicate file 

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/dam-app#144]
![image](https://user-images.githubusercontent.com/79819354/212050920-8c1683b4-5af6-4afe-90a1-7d09eb2ace3a.png)

**Comment by OscarIboy** [comment]
Now when a duplicate image is added a "(1, 2, 3...)" is added to the image.
![Captura de pantalla -2023-06-01 11-52-53](https://github.com/aesirxio/dam-app/assets/8058963/04ca53fe-76be-4e2e-8503-07d33a190e70)
