### ISSUE TITLE
Message status - Version 2

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#146]
![image](https://user-images.githubusercontent.com/44457418/212270824-6e4e5ef7-9141-4e18-b721-94744adef1f9.png)
Design at 
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=552%3A1816&t=h8aObSmTfUsu9fNt-0

**Comment by huynhngocgiau** [comment]
Not update yet
![style](https://user-images.githubusercontent.com/79819354/215022997-88839035-70ac-4867-8207-0aea50d02250.png)

**Comment by huynhngocgiau** [comment]
Successfull: work
![successful](https://user-images.githubusercontent.com/79819354/215981837-2b89e5bf-7563-4491-b1fe-bb41e5ebe48c.png)
Error: text color #C8192E
![error](https://user-images.githubusercontent.com/79819354/215982621-b1f7a994-bd00-4e6a-97a6-6f8959db8502.png)

**Comment by huynhngocgiau** [comment]
Error: work
![image](https://user-images.githubusercontent.com/79819354/216555370-a5fa11d6-b9c2-4eaa-a016-d62290de630a.png)
Warn: work
![image](https://user-images.githubusercontent.com/79819354/216557672-a425be42-4bf9-4241-89bb-cae9a7ecd7a8.png)
