### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/dam-app#17]
https://www.figma.com/proto/OAcpwQSGND0t6Dswi3ZTKP/AESIR_DAM?page-id=0%3A1&node-id=89%3A12713&viewport=409%2C-3189%2C0.5&scaling=min-zoom

**Comment by jatitoam** [comment]
hi @kakahuy113 this one is awaiting review but no PR, what is the PR?

**Comment by kakahuy113** [comment]
@vinhdigital is the one handle it

**Comment by jatitoam** [comment]
Ok I see it... thanks

**Comment by NguyenTrang091296** [comment]
Hi @kakahuy113 I cannot upload avatar and update profile show error 'Something went wrong.' 
https://youtu.be/0aaZP_COitc
