### ISSUE TITLE
Left menu - Icon, active sub-item

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#186]
Check icon My Assets, icon folder 
![image](https://user-images.githubusercontent.com/44457418/216541556-dc0266bf-7ea0-4915-a815-20262ec9eb5a.png)
Check Ion sub-folder 
![image](https://user-images.githubusercontent.com/44457418/216542050-44588f09-81b5-4f69-9058-48c140084c48.png)
Remove the color parent folder when user active on the child folder 
![image](https://user-images.githubusercontent.com/44457418/216542238-29709648-fb5a-4207-8518-6051f4409c67.png)
Remove the font-weight when user hover on the folder - font-weight only show on when active folder

Design ![image](https://user-images.githubusercontent.com/44457418/216541781-307f7a95-f021-4aa8-9ea1-9cf2fb9e745b.png)

**Comment by kakahuy113** [comment]
@TrucNguyenx please confirm when child active parent will be remove color

**Comment by TrucNguyenx** [comment]
@kakahuy113 @VanTrieuThanh 
When child active, parent must be active too
=> Folder con nào đang được chọn có nằm trong folder cha, thì cha + con đó phải active màu nha

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/219319259-cb867b07-077d-47e1-8bd1-e12883276221.png)

**Comment by kakahuy113** [comment]
dulicate #214
