### ISSUE TITLE
[UI] Move to folder - Change color hover / defaut

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#195]
Improve UI - 'Move to folder' 
- Currently:
![Image](https://user-images.githubusercontent.com/118497336/217472199-c0070f1f-27c2-4464-af55-1343e3f8aecd.png)

- Design:

![Image](https://user-images.githubusercontent.com/118497336/217474830-b6eb2f6b-88c8-4128-90de-c3fa20165303.png)

Link: https://www.figma.com/proto/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?page-id=552%3A1816&node-id=4681%3A25882&viewport=-8808%2C2780%2C1&scaling=min-zoom

cc @huynhngocgiau

**Comment by huynhngocgiau** [comment]
conflict a @kakahuy113

**Comment by huynhngocgiau** [comment]
Please check again a @kakahuy113 
1. Add icon "Back"
2. Delete "Cancel", "Move to folder" button
![image](https://user-images.githubusercontent.com/79819354/220251427-b8bdf3b5-26b3-49ad-801f-c15f24701222.png)

**Comment by kakahuy113** [comment]
icon back can not be in root folder e and if dont have cancel or movetofolder button what the view do e ? c @TrucNguyenx just demo the hover and active and keep the same from what we get please ask truc for detail e

**Comment by huynhngocgiau** [comment]
Location for icon and text @kakahuy113 
![image](https://user-images.githubusercontent.com/79819354/220261072-5105f03c-d3ce-4c27-b2a1-a3c9219e588c.png)

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/220277406-6d878135-b5d1-4fc3-9e22-6ea6eae3397d.png)

**Comment by VanTrieuThanh** [comment]
Has update on the docker-qa file 
![Screenshot from 2023-02-22 09-56-36](https://user-images.githubusercontent.com/44457418/220510165-a2616759-42eb-458d-bc37-5a74fad4fdf6.png)

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/220539716-6dd8126d-1d0a-4cc3-b00c-e55d16a2cc2f.png)
