### ISSUE TITLE
[UI] Animation - Drop to upload

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#196]
Change button + icon color:
From this
![Image](https://user-images.githubusercontent.com/118497336/217484509-d0370a9b-04a3-4f75-9a70-307d535edfa5.png)

To this:
![Image](https://user-images.githubusercontent.com/118497336/217484607-752837d2-f482-48b6-a38c-faca095c8f34.png)

**Comment by huynhngocgiau** [comment]
![image](https://user-images.githubusercontent.com/79819354/220314710-a2451774-a8d1-4d2a-ac9d-53c7e7e5eb54.png)

**Comment by VanTrieuThanh** [comment]
![Screenshot from 2023-02-22 09-43-19](https://user-images.githubusercontent.com/44457418/220508008-615c5df3-fe3d-404d-9a92-d5b1ce354d3d.png)
Icon Drop to upload image folder has changed
