### ISSUE TITLE
The width of search field too wide

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dam-app#197]
![Image](https://user-images.githubusercontent.com/30283123/217489390-844a24f0-830b-48ad-b7b1-3f9ba8cde78d.png)
 The width of search field too wide

**Comment by VanTrieuThanh** [comment]
the width has update 
![image](https://user-images.githubusercontent.com/44457418/220514165-eb834321-6f70-4474-a3a5-4d16c8711b49.png)
