### ISSUE TITLE
Border the menu bar

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dam-app#198]
![Image](https://user-images.githubusercontent.com/30283123/217492335-bfd46ea2-c001-4311-b409-aac026106b7c.png)

 Following the design 
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=552%3A1816&t=YH6mdnhfpCbi1kbb-0

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/219997448-ec062894-294b-4b07-959f-c506595801ef.png)
