### ISSUE TITLE
[UI] Folder (More view)

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#199]
Add more padding for this
Height: 40px

![Image](https://user-images.githubusercontent.com/118497336/217501054-0d3ea2f3-d713-43ab-8481-261e6742e914.png)

**Comment by VanTrieuThanh** [comment]
the padding has update ![Screenshot from 2023-02-22 10-23-39](https://user-images.githubusercontent.com/44457418/220513394-a5269340-ffa1-4c00-93cc-0af93477486e.png)
