### ISSUE TITLE
The dropdowns should be as unique format

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dam-app#200]
When I click on dropdown of Type: the upper line locates below

![Image](https://user-images.githubusercontent.com/30283123/218003821-feeb42c7-5dfb-4d66-8740-71989bef42ae.png)

But for Choose an action, the dropdown cover the button

![Image](https://user-images.githubusercontent.com/30283123/218003792-cc2d5759-cbbc-40bf-92f4-f004cb76cf0e.png)

**Comment by kakahuy113** [comment]
duplicate #214

**Comment by huynhngocgiau** [comment]
I will close when this issue #214 is closed

**Comment by huynhngocgiau** [comment]
#214 close
