### ISSUE TITLE
Wrong UI - Left menu

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/dam-app#210]
Please check again design

Spacing for icon in button and text
Location of icons
![image](https://user-images.githubusercontent.com/79819354/219323958-31836c74-eea6-4b5c-a4f7-649a0bc98ff7.png)

**Comment by kakahuy113** [comment]
please provide detail e @huynhngocgiau

**Comment by kakahuy113** [comment]
duplicate #214
