### ISSUE TITLE
UI - Folder detail - Hover color 

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/dam-app#212]
1. Hover color
2. Size
![image](https://user-images.githubusercontent.com/79819354/219550699-d9f03aa2-8204-4475-bd2d-bb88c8794152.png)

**Comment by TrucNguyenx** [comment]
Please reduce padding of the box to 16px 
-> Giảm padding của box khi chuột trái còn 16px @kakahuy113

**Comment by VanTrieuThanh** [comment]
Change border-radius:5px for file and folder 
![image](https://user-images.githubusercontent.com/44457418/220517797-762fe917-d637-41eb-99c9-f07f17d74ddd.png)
Hover not active when user hover on the file or folder

**Comment by TrucNguyenx** [comment]
- Hover: Line
- Select: Line + number select file @kakahuy113

**Comment by huynhngocgiau** [comment]
Spacing and location for icon, text
![image](https://user-images.githubusercontent.com/79819354/220833807-53e25607-ab4b-4e81-8a8f-46a72a83b949.png)

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/220890085-575fbb50-04d3-4ca9-af68-9442521b1dfa.png)
