### ISSUE TITLE
UI improve

### ISSUE THREAD

**Issue by kakahuy113** [aesirxio/dam-app#214]
#67 #83 #186 #69 #210 #200 #198

**Comment by kakahuy113** [comment]
help me check if issues above is done close this task

**Comment by kakahuy113** [comment]
you need to update the detail instead of create new issues e @huynhngocgiau i see many sidebar task so i put it together and now if you see what can be in 1 issues and that issues is not merge or close yet please input in one issues for clearly purpose

**Comment by kakahuy113** [comment]
e @huynhngocgiau  e what do you mean about 4 you want it full width ?

**Comment by kakahuy113** [comment]
and 2 i already change to 5% as the last time we spoke ?

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/220269986-4fffada8-98e8-4852-848f-569b130264fb.png)
