### ISSUE TITLE
Login - Remove Authentication Login

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/dam-app#215]
- Only use AesirX SSO.
- Change the text to "Sign in with AesirX SSO"

![Image](https://user-images.githubusercontent.com/2959010/219596085-df225c4b-ffa1-4e2b-913d-ab51f2de12ce.png)

**Comment by VanTrieuThanh** [comment]
help me update it

**Comment by VanTrieuThanh** [comment]
Remove the "Aesirx" in the button 
![image](https://user-images.githubusercontent.com/44457418/220542324-e3ebda84-f5ce-403a-ab5b-ee6502c7339e.png)
Missing the background in the design 
![image](https://user-images.githubusercontent.com/44457418/220541925-832ad6ab-53d4-4366-a255-55a33ec6f9e8.png)
Text in button should be 18px
![Screenshot from 2023-02-22 13-42-28](https://user-images.githubusercontent.com/44457418/220543384-0466d28c-1148-44ee-947a-f49804d22036.png)
