### ISSUE TITLE
The collection list is not displayed as a tree

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/dam-app#23]
The "product IMG" collection have child collection but not display on menu with sub-collection

![Image](https://user-images.githubusercontent.com/39818849/192972971-d5665441-0d3a-4f29-bb9f-411f01317ce4.png)

![Image](https://user-images.githubusercontent.com/39818849/192973283-967d4bcb-e9f9-47ae-ab24-e3d56b1393bb.png)

**Comment by VanTrieuThanh** [comment]
the tree not display on app 
![image](https://user-images.githubusercontent.com/44457418/204467759-cf10e521-f934-4450-87c2-5a43b3c24ba7.png)
