### ISSUE TITLE
DAM integration PIM - Not background

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#237]
DAM app 
![Image](https://user-images.githubusercontent.com/44457418/222045999-f026ae3b-8d1a-4e98-af33-daee8fcb1cd6.png)
DAM integration PIM 
![Image](https://user-images.githubusercontent.com/44457418/222046108-40d19330-6bda-4fb1-8814-9e62d4712388.png)

**Comment by VanTrieuThanh** [comment]
it still not working on docker qa

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/225505025-ad059f61-d226-475c-b0f2-ae5ef81875da.png)
