### ISSUE TITLE
DAM integration PIM - Translate

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/dam-app#238]
Thai
![image](https://user-images.githubusercontent.com/79819354/222047021-873c9ac3-6722-4d50-a660-8a4524ecea60.png)

**Comment by huynhngocgiau** [comment]
DK
![image](https://user-images.githubusercontent.com/79819354/222659522-f46e1397-f079-4379-8c08-f29e25a20656.png)

**Comment by kakahuy113** [comment]
@huynhngocgiau  i had fix if still not update please assign to a @lklong709  with title change language code with standard format

**Comment by huynhngocgiau** [comment]
DK
![image](https://user-images.githubusercontent.com/79819354/224980074-0dcbc400-f401-45b1-8325-18cf481abba6.png)

**Comment by huynhngocgiau** [comment]
I will close this issue and create new issue

**Comment by kakahuy113** [comment]
not need em let a Long check and then close this just create a task and comment relate to this
