### ISSUE TITLE
DAM with UX

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/dam-app#298]
https://www.figma.com/proto/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?page-id=552%3A1816&type=design&node-id=13733-189703&t=7bsaDmNfH1adko9V-0&scaling=min-zoom

**Comment by nikolagajski** [comment]
@toanredweb on testing i see that the the sorting by Last modified is not working correctly...
it is always sorting by Creation date...
![image](https://github.com/aesirxio/dam-app/assets/21126820/4c5a2f13-ace5-47da-8511-1f8f176e13d8)

**Comment by nikolagajski** [comment]
in an empty folder there is no warning for the Maximum upload size like it is in Figma on page 15
![image](https://github.com/aesirxio/dam-app/assets/21126820/1e8f803e-0fbc-4629-a9e4-b4bdceca0047)

**Comment by nikolagajski** [comment]
There is no preview of the images that are in that folder like on page 17 in Figma
![image](https://github.com/aesirxio/dam-app/assets/21126820/9a1e632b-50fd-41f8-acbb-b0b3a254669a)

**Comment by nikolagajski** [comment]
Needs adjustments for Tab version and Mobile version compared to Figma 26,27,29,30
![image](https://github.com/aesirxio/dam-app/assets/21126820/7144d51d-44e7-466f-912d-754f44ef4464)
