### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/dam-app#4]
https://www.figma.com/proto/OAcpwQSGND0t6Dswi3ZTKP/AESIR_DAM?page-id=0%3A1&node-id=57%3A1893&viewport=409%2C-3189%2C0.5&scaling=min-zoom
https://www.figma.com/proto/OAcpwQSGND0t6Dswi3ZTKP/AESIR_DAM?page-id=0%3A1&node-id=26%3A3168&viewport=409%2C-3189%2C0.5&scaling=min-zoom

**Comment by NguyenTrang091296** [comment]
I checked and I see it is not working
https://youtu.be/_uLBFt4fY5I

**Comment by NguyenTrang091296** [comment]
I checked and I see it is not working 
https://youtu.be/UGIUJfSsrLI
