### ISSUE TITLE
AesirX DAM Translations

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/dam-app#43]

**Comment by VanTrieuThanh** [comment]
The language translate not translate all the text
![image](https://user-images.githubusercontent.com/44457418/203969285-206393a6-f458-44c2-8be5-e39227c861a4.png)
![image](https://user-images.githubusercontent.com/44457418/203969418-f79c992e-a2f8-4018-8c3a-4eb52a6f3bc0.png)
![image](https://user-images.githubusercontent.com/44457418/203969529-3a68a116-db54-4f90-985e-5fc5e81b1acc.png)

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/212289412-06425c2b-f1a4-45b5-9e7f-44738cb44efb.png)
![image](https://user-images.githubusercontent.com/44457418/212289559-f74d7a99-aa7e-453c-bc22-8a936123fc82.png)
![image](https://user-images.githubusercontent.com/44457418/212289933-5251444a-b69c-403e-84a6-1298f963acf6.png)

**Comment by kakahuy113** [comment]
duplicate #141

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/216881624-02d12870-cf25-4b91-95e0-4ed536253339.png)
