### ISSUE TITLE
Change position main CTA + fix color

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#64]

**Comment by TrucNguyenx** [comment]
Change the main CTA (green) left to right like the design

Đổi vị trí CTA xanh sang phía bên phải như link design: https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=552%3A1816&t=P8AtoRFu91gsVDU2-1

![Image](https://user-images.githubusercontent.com/118497336/202642892-728631c3-6190-4954-b2fe-27e3a9bf1f8d.png)

**Comment by TrucNguyenx** [comment]
Change 'Create folder' btn to White

![Image](https://user-images.githubusercontent.com/118497336/202685296-ac207628-1c7d-406d-9d05-4692f43d6969.png)

**Comment by VanTrieuThanh** [comment]
the background color for "Create Folder" button not change 
![image](https://user-images.githubusercontent.com/44457418/203971714-1ba796b7-6819-4e0b-ad7d-29c5a1a753db.png)
