### ISSUE TITLE
Missing search box and error account

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#65]

**Comment by TrucNguyenx** [comment]
Demo: Missing search box and error account (not display avatar)

![Image](https://user-images.githubusercontent.com/118497336/202643584-e04844ff-85a1-4bf6-9ecb-1077aa37fec1.png)

Design: 


![Image](https://user-images.githubusercontent.com/118497336/202643743-37f70fb6-d506-4552-9eed-f0aaad23b0bf.png)

**Comment by NguyenTrang091296** [comment]
I checked on local site and I see it has been fixed 
![Screenshot from 2022-11-29 11-22-53](https://user-images.githubusercontent.com/39818849/204438510-7bf924fd-eaae-45c1-b21b-4340a628de07.png)
