### ISSUE TITLE
Improve sidebar

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#66]

**Comment by TrucNguyenx** [comment]
Demo: 
Improve sidebar
- Color
- Line color
- Capitalize font 
- Missing Help center


![Image](https://user-images.githubusercontent.com/118497336/202644428-871cd4bb-7d3e-4f5c-ae75-ff14d7412b83.png)


Design: 


![Image](https://user-images.githubusercontent.com/118497336/202644466-044f35ec-064f-45b3-b322-3d42d499711a.png)

**Comment by kakahuy113** [comment]
@TrucNguyenx we don't have help center yet

**Comment by TrucNguyenx** [comment]
@kakahuy113 just do it like BI but not link for now, cause you will forget :)))

**Comment by TrucNguyenx** [comment]
Bug @kakahuy113 
-> Khi thu nhỏ sidebar bị rớt text nè e, cho nó hiển thị icon thôi


![Image](https://user-images.githubusercontent.com/118497336/202654140-671b872f-8de4-413f-b301-0a532b3a8136.png)

**Comment by VanTrieuThanh** [comment]
still not fix on DEV branch 
![image](https://user-images.githubusercontent.com/44457418/204180579-590be6ef-3c5b-4e7b-bada-dde9f0ae5cc6.png)

**Comment by NguyenTrang091296** [comment]
Please help me fix Capitalize font
change icon same as design 
![image](https://user-images.githubusercontent.com/39818849/212020785-95add131-7e55-4c50-92fd-3a2460969dc3.png)
