### ISSUE TITLE
DAM demo - Start page 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#68]
Error image
Change the color for required icon
![image](https://user-images.githubusercontent.com/44457418/202647053-8b20b39d-9d16-48af-9650-e3495b0d050b.png)
Font-size 
![image](https://user-images.githubusercontent.com/44457418/202647419-f52ee4bd-18e6-4c5c-8869-40697ecf1872.png)
![image](https://user-images.githubusercontent.com/44457418/202647515-f0d98580-080d-4989-9fb1-dc308701ba8b.png)
Change the Upper Case 
![image](https://user-images.githubusercontent.com/44457418/202647749-c8682a8d-c355-49bb-a46b-0400fd990d1a.png)

**Comment by OscarIboy** [comment]
In the current demo-Dam, SSO is being used and the color of "required icon" has already been changed.

![Captura de pantalla -2023-06-01 12-44-59](https://github.com/aesirxio/dam-app/assets/8058963/b64dfd71-b7c7-4675-8d54-3778e1fb8413)
![Captura de pantalla -2023-06-01 12-45-24](https://github.com/aesirxio/dam-app/assets/8058963/bf1a4ba3-3c96-45cb-b670-913787053aa5)
