### ISSUE TITLE
Bug when upload file

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#70]
When click Upload file:

![Image](https://user-images.githubusercontent.com/118497336/202649455-a8198239-65b3-4af3-9d10-a4575c020e8e.png)

**Comment by kakahuy113** [comment]
@VanTrieuThanh please assign to BE and pass check again in post man

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/204458178-6b3f9193-b4fb-4243-a0e1-594e6e549f7b.png)
After add code https://github.com/redCOMPONENT-COM/redCORE/pull/925 I try the upload file successful on my local 
![image](https://user-images.githubusercontent.com/44457418/204462196-9c33569c-1543-4e62-8001-46d35feb6fea.png)
