### ISSUE TITLE
Fix: Upload/Create folder

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#72]
1. Only show when right click on mouse
-> Chỉ hiện khi click chuột phải

2. Check hover color: change color when hover
-> Đổi màu khi hover 

![Image](https://user-images.githubusercontent.com/118497336/202653001-41b866cc-9b31-4928-a4c9-a11ae0b510a9.png)

3. Wrong prototype when create folder
Demo 
![Image](https://user-images.githubusercontent.com/118497336/202653479-61417668-61fc-4ec4-9b8b-cea3bb80a750.png)

Design: 
![Image](https://user-images.githubusercontent.com/118497336/202653497-ce3cfb5f-0b0c-43c8-bf53-343c553618e1.png)

**Comment by kakahuy113** [comment]
duplicate with #115

**Comment by huynhngocgiau** [comment]
Wrong prototype when create folder
App
![image](https://user-images.githubusercontent.com/79819354/219544328-bedbbb7f-5b22-49fe-8e59-501d288e1b05.png)
Design
![image](https://user-images.githubusercontent.com/79819354/219544596-d12cc504-3728-4d5a-9216-f265d9526c54.png)

**Comment by huynhngocgiau** [comment]
Not the same design a @kakahuy113 
1. Border: 2px solid #1AB394
2. Input field size
3. Message will be displayed after entering the folder name

Actual:
![image](https://user-images.githubusercontent.com/79819354/219871501-332cf839-3e99-4bba-afc0-1d891d7fdbe9.png)

Design:
![image](https://user-images.githubusercontent.com/79819354/219871458-8e6947de-f56e-4b90-9fe4-ce59e05e1432.png)

**Comment by kakahuy113** [comment]
@TrucNguyenx please ask her

**Comment by TrucNguyenx** [comment]
- Input field size = 80% main box
- Done with flow create folder with loading in BE

**Comment by huynhngocgiau** [comment]
Delete message

**Comment by VanTrieuThanh** [comment]
Input field 80%
![image](https://user-images.githubusercontent.com/44457418/220511450-e3f77d9e-30f1-421a-8149-d161002638d4.png)
The message create success just show when user click on the "Enter" on keyboard. Current, click on the keyboard or click mouse on the other place in app the message has show on -> remove action click on the other place in app to create folder

**Comment by kakahuy113** [comment]
the input already 80% of the box size, about remove mouse on other place please discuss with @TrucNguyenx if just only enter maybe not good UX c @VanTrieuThanh

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/220543962-98eece68-5b08-4b8f-9dce-8515b6e2d9bb.png)
