### ISSUE TITLE
Wrong UI dropfile / select file detail

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#73]
Demo:

![Image](https://user-images.githubusercontent.com/118497336/202658315-74043cf8-3f97-42f4-b430-1bef1afad88e.png)

Design:

![Image](https://user-images.githubusercontent.com/118497336/202658434-e33eaabd-0e2d-46bd-b3c9-1e5d9da80897.png)

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/204457470-fd9c8f1a-50da-4d7d-8163-345eb7400c8b.png)
don't update on the my local

**Comment by kakahuy113** [comment]
maximum upload file is remove because there is no maximum

**Comment by TrucNguyenx** [comment]
@kakahuy113 not about the text "Maximum...", it the color of the background upload file

**Comment by NguyenTrang091296** [comment]
"Drop files anywhere to upload" and 'Select file' have color : #282831
"or" have color:  #828282
cc @kakahuy113 please help me fix
