### ISSUE TITLE
Menu bar - And spacing for text

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dam-app#75]
![image](https://user-images.githubusercontent.com/44457418/202677503-2f43b658-8bf3-49a3-9fc4-bdafee4fa689.png)

**Comment by NguyenTrang091296** [comment]
![image](https://user-images.githubusercontent.com/39818849/216287573-4b1f04ec-8db6-43e1-ad59-a802cafecccf.png)
I checked and I see it has been fixed
