### ISSUE TITLE
Folder detail - preview media

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/dam-app#8]
Preview: https://www.figma.com/proto/OAcpwQSGND0t6Dswi3ZTKP/AESIR_DAM?page-id=0%3A1&node-id=169%3A3374&viewport=409%2C-3189%2C0.5&scaling=min-zoom

**Comment by NguyenTrang091296** [comment]
preview image with the box too big and delete button, update button not working
![image](https://user-images.githubusercontent.com/39818849/193212489-60ec484c-e5a5-4cde-90e4-113b64acd500.png)
