### ISSUE TITLE
Wrong UI when switch List/Thumb

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#82]
Background change when switch List/Thumb view
-> Màu bg bị đổi khi view bằng list / thumb
![Image](https://user-images.githubusercontent.com/118497336/203683265-af0fdee8-9c91-4350-a3d5-0fa42901bafd.png)

![Image](https://user-images.githubusercontent.com/118497336/203683281-7ce0b5c9-c665-47b4-a660-c34f67b7c1a3.png)

Design: 

![Image](https://user-images.githubusercontent.com/118497336/203683373-fcb9e432-bcdf-4fc6-9c11-fda55fdc2415.png)

**Comment by TrucNguyenx** [comment]
One more: wrong icon list/thumb
-> Check dùm chị luôn nha em @VanTrieuThanh

**Comment by NguyenTrang091296** [comment]
Hi @kakahuy113 Please help me change icon List and thumb to same as design 
![image](https://user-images.githubusercontent.com/39818849/204439724-ae664496-34ab-4a30-929b-c8c9abedaf76.png)

**Comment by thaoredweb** [comment]
It is okie
![image](https://user-images.githubusercontent.com/30283123/217491925-f5d5f9bb-5f16-4e9e-937a-ab88e89d48f4.png)
