### ISSUE TITLE
Fix: color sub folder: sidebar

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/dam-app#83]
Wrong color when show sub folder on sidebar:
-> Màu khi view dropdown sai nha

![Image](https://user-images.githubusercontent.com/118497336/203684004-2a2cc5d9-154b-4f48-b5bc-eedcb87e2497.png)

Design: 
![Image](https://user-images.githubusercontent.com/118497336/203684039-87ca3a52-55a1-40e9-8157-63244973d737.png)

**Comment by VanTrieuThanh** [comment]
missing color in sub-menu
![image](https://user-images.githubusercontent.com/44457418/204769218-8f52ada8-8295-4a3e-859e-229694ee4e7c.png)

**Comment by NguyenTrang091296** [comment]
Hi @kakahuy113 Please help me fix only active menu item when it is opening

**Comment by kakahuy113** [comment]
@NguyenTrang091296 @TrucNguyenx had confirm me active only when it active open not active

**Comment by kakahuy113** [comment]
but i need open it when it being choose

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/219292507-38e9279d-ed13-4340-9866-845f2598d64a.png)

**Comment by kakahuy113** [comment]
duplicate #214
