### ISSUE TITLE
Create folder / file

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/dam-app#9]
https://www.figma.com/proto/OAcpwQSGND0t6Dswi3ZTKP/AESIR_DAM?page-id=0%3A1&node-id=57%3A1893&viewport=409%2C-3189%2C0.5&scaling=min-zoom
https://www.figma.com/proto/OAcpwQSGND0t6Dswi3ZTKP/AESIR_DAM?page-id=0%3A1&node-id=26%3A3341&viewport=409%2C-3189%2C0.5&scaling=min-zoom

**Comment by NguyenTrang091296** [comment]
I click on "Create folder" it will be created success with "new folder" name but I cannot change folder name
https://youtu.be/ZiYQfGm4UR0
