### ISSUE TITLE
DAM - Modal - Broken layout when go to child folder

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/dam-app#98]
**

![Image](https://user-images.githubusercontent.com/39818849/209049555-03c1f8cd-8a34-4cd9-8f40-94170b43596d.png)

**

**Comment by huynhngocgiau** [comment]
![image](https://user-images.githubusercontent.com/79819354/212049937-8c715a3a-3cc9-404a-a515-c6d3f0e50ac9.png)
