### ISSUE TITLE
DAM - Modal - Missing cancel and Insert to post button

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/dam-app#99]
Actual result:

![Image](https://user-images.githubusercontent.com/39818849/209049992-076c615a-fe5c-48f6-9ce6-7d6d870f0118.png)

Expected output:

![Image](https://user-images.githubusercontent.com/39818849/209050052-f87d0bda-980d-4ab8-bd48-680132ee5c78.png)

**Comment by VanTrieuThanh** [comment]
Current, step select image for DAM integration will don't have 
[Video-Thu-Mar-23-2023-11-56-49.webm](https://user-images.githubusercontent.com/44457418/227108284-67cc6fbc-c888-4539-9a78-3825dfd5e602.webm)
